---
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# --> (Optional) Change log level and format here ...
#     - level: [TRACE, DEBUG, INFO, WARN, ERROR, FATAL]
log:
 level: DEBUG

certificatesResolvers:
  letsencrypt:
    acme:
      email: email@domain.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web
 
# <--

# --> (Optional) Enable accesslog here ...
# accesslog: {}
# <--

# --> (Optional) Enable API and Dashboard here, don't do in production
api:
   dashboard: true
   insecure: true
# <--

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # --> (Optional) Redirect all HTTP to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    # <--
  websecure:
    address: :443

disablePropagationCheck: false

providers:
  docker:
    exposedByDefault: false  # <-- (Optional) Change this to true if you want to expose all services
    # Specify discovery network - This ensures correct name resolving and possible issues with containers, that are in multiple networks.
    # E.g. Database container in a separate network and a container in the frontend and database network.
    network: YOUR_NETWORK
  file:
    directory: /etc/traefik/dynamic
    watch: true
