version: "3.3"

services:

  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3306:3306"
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - rnrgfx
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  rnrgfx:
    external: true  # <-- (Optional) Change this to false if you want to create a new network
