---
services:
  nginx:
    image: nginx:1.26.3-alpine-slim
    container_name: nginx    
    volumes:
      # - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./data:/usr/share/nginx/html
    labels:
      - traefik.enable=true
      - traefik.http.services.nginx.loadbalancer.server.port=443
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.rule=Host(`nginx.da9l.dk`)
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certresolver=cloudflare
      - traefik.http.routers.nginx.service=nginx

    #  - traefik.http.services.nginx-un.loadbalancer.server.port=80
    #  - traefik.http.routers.nginx-un.entrypoints=web
    #  - traefik.http.routers.nginx-un.rule=Host(`nginx.da9l.dk`)
    #  - traefik.http.routers.nginx-un.service=nginx-un
    networks:
      - rnrgfx
    restart: unless-stopped

networks:
  rnrgfx:
    external: true
